version: 0.2

phases:
  pre_build:
    commands:
      - echo "Commit Details:"
      - echo "Commit ID: $CODEBUILD_RESOLVED_SOURCE_VERSION"
      - echo "Branch: $CODEBUILD_WEBHOOK_HEAD_REF"

  build:
    commands:
      - echo "Building the project..."
