version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing git..."
      - yum install -y git || apt-get update && apt-get install -y git
      - echo "Fetching commit history..."
      - git log -n 5 --pretty=format:"%h - %an, %ar : %s"

  build:
    commands:
      - echo "Building the project..."
