version: 0.2

env:
  variables:
    GITHUB_REPO: "Dilipsurage09/lambda_layar_cicd"
  parameter-store:
    GITHUB_TOKEN: "/codebuild/github/token"  # Store your token in Parameter Store

phases:
  install:
    commands:
      - echo "Installing Dependencies"
      - apt-get update && apt-get install -y curl jq git

  pre_build:
    commands:
      - echo "Configuring Git to Fetch Full History"
      - git config --global credential.helper '!f() { echo "username=Dilipsurage09"; echo "password=$GITHUB_TOKEN"; }; f'
      - git remote set-url origin https://github.com/$GITHUB_REPO.git
      - git fetch --unshallow  # Fetch full commit history
      - echo "Displaying Git Commit History"
      - git log --pretty=oneline -n 5  # Display last 5 commits
      - echo "End of Git Commit History"

  build:
    commands:
      - echo "Build Phase Started"
      - echo "Your build commands go here"
      - echo "Build Phase Completed"

artifacts:
  files:
    - '**/*'
