version: 0.2

phases:
  pre_build:
    commands:
      - echo "Fetching commit details..."
      - echo "Commit ID: $CODEBUILD_RESOLVED_SOURCE_VERSION"
      - echo "Branch: $CODEBUILD_WEBHOOK_HEAD_REF"
      - echo "Commit URL: https://github.com/Dilipsurage09/lambda_layar_cicd/commit/$CODEBUILD_RESOLVED_SOURCE_VERSION"

  build:
    commands:
      - echo "Building the project..."
