version: 0.2

env:
  secrets-manager:
    GITHUB_TOKEN: "/codebuild/github-token"

phases:
  pre_build:
    commands:
      - echo "Setting up Git configuration"
      - git config --global user.name "codebuild-bot"
      - git config --global user.email "codebuild-bot@example.com"
      - git remote set-url origin https://$GITHUB_TOKEN@github.com/Dilipsurage/lambda_layar_cicd.git
      - echo "Fetching full commit history"
      - git fetch --unshallow
      
  build:
    commands:
      - echo "Displaying Git commit history"
      - git log --oneline -n 10

artifacts:
  files:
    - '**/*'
