version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing git..."
      - yum install -y git # For Amazon Linux
      - apt-get update && apt-get install -y git # For Ubuntu
      - echo "Fetching commit history..."
      - git log -n 5 --pretty=format:"%h - %an, %ar : %s" # Show last 5 commits

  build:
    commands:
      - echo "Building the project..."
