version: 0.2

phases:
  install:
    commands:
      - echo "Installing Dependencies"
      - npm install
  build:
    commands:
      - echo "Preparing Lambda Layer"
      - mkdir -p layer/nodejs
      - cp -R node_modules package.json layer/nodejs/
      - cd layer && zip -r layer.zip nodejs
      - aws lambda publish-layer-version --layer-name layar_cicd --zip-file fileb://layer.zip --compatible-runtimes nodejs22.x
      - echo "Packaging Lambda Function"
      - zip -r function.zip index.js
      - aws lambda update-function-code --function-name lambda_layar_cicd --zip-file fileb://function.zip
