version: 0.2

phases:
  install:
    commands:
      - echo "Installing Dependencies and Zip Utility"
      - apt-get update && apt-get install -y zip
      - echo "Navigating to Project Directory"
      - cd lambda-layer-project
      - ls -la  # Check if package.json is here
      - npm install
      - cd ..

  build:
    commands:
      - echo "Preparing Lambda Layer"
      - mkdir -p lambda-layer-project/layer/nodejs
      - cp -R lambda-layer-project/node_modules lambda-layer-project/package.json lambda-layer-project/layer/nodejs/
      - cd lambda-layer-project/layer
      - ls -la  # Verify nodejs directory content
      - zip -r layer.zip nodejs
      - ls -la  # Confirm that layer.zip is created
      - cd ..
      - mv layer/layer.zip ../layer.zip  # Move layer.zip to the root directory
      - echo "Publishing Lambda Layer"
      - ls -la ../  # Confirm layer.zip is in the root directory
      - aws lambda publish-layer-version --layer-name layar_cicd --zip-file fileb://../layer.zip --compatible-runtimes nodejs18.x
      - echo "Packaging Lambda Function"
      - zip -r ../function.zip index.js
      - ls -la ../  # Confirm function.zip is in the root directory
      - aws lambda update-function-code --function-name lambda_layar_cicd --zip-file fileb://../function.zip

artifacts:
  files:
    - layer.zip
    - function.zip
