version: 0.2

phases:
  pre_build:
    commands:
      - echo "Navigating to source directory..."
      - cd $CODEBUILD_SRC_DIR
      - echo "Showing recent commit history:"
      - git log -n 5 --oneline

  build:
    commands:
      - echo "Building the project..."
