version: 0.2

env:
  variables:
    GITHUB_REPO: "Dilipsurage09/lambda_layar_cicd"

phases:
  install:
    commands:
      - echo "Installing Dependencies"
      - apt-get update && apt-get install -y curl jq

  pre_build:
    commands:
      - echo "Fetching Git Commit History from GitHub API"
      - export COMMIT_ID=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo "Commit ID: $COMMIT_ID"
      - echo "Fetching commit details"
      - curl -s "https://api.github.com/repos/$GITHUB_REPO/commits/$COMMIT_ID" | jq '.commit | {message, author}'
      - echo "End of Git Commit History"

  build:
    commands:
      - echo "Starting Build Phase"
      - echo "Preparing Lambda Layer"
      - mkdir -p lambda-layer-project/layer/nodejs
      - cp -R lambda-layer-project/node_modules lambda-layer-project/package.json lambda-layer-project/layer/nodejs/
      - cd lambda-layer-project/layer
      - ls -la
      - zip -r layer.zip nodejs
      - ls -la
      - mv layer.zip ../../layer.zip
      - cd ../..
      - echo "Publishing Lambda Layer"
      - ls -la
      - aws lambda publish-layer-version --layer-name layar_cicd --zip-file fileb://layer.zip --compatible-runtimes nodejs22.x
      - echo "Packaging Lambda Function"
      - zip -r function.zip index.js
      - ls -la
      - aws lambda update-function-code --function-name lambda_layar_cicd --zip-file fileb://function.zip

artifacts:
  files:
    - layer.zip
    - function.zip
