version: 0.2

phases:
  install:
    commands:
      - echo "Navigating to Project Directory"
      - cd lambda-layer-project
      - ls -la  # Check if package.json is here
      - npm install
      - cd ..
  build:
    commands:
      - echo "Preparing Lambda Layer"
      - mkdir -p lambda-layer-project/layer/nodejs
      - cp -R lambda-layer-project/node_modules lambda-layer-project/package.json lambda-layer-project/layer/nodejs/
      - cd lambda-layer-project/layer
      - echo "Checking contents of layer directory"
      - ls -la  # Check if nodejs directory is here
      - ls -la nodejs  # Check contents of nodejs directory
      - echo "Setting permissions"
      - chmod -R 755 nodejs  # Ensure proper permissions
      - echo "Creating Layer ZIP"
      - zip -r layer.zip nodejs
      - mv layer.zip ../layer.zip  # Move zip to correct directory
      - cd ../..
      - echo "Publishing Lambda Layer"
      - aws lambda publish-layer-version --layer-name layar_cicd --zip-file fileb://lambda-layer-project/layer.zip --compatible-runtimes nodejs22.x
      - echo "Packaging Lambda Function"
      - zip -r function.zip lambda-layer-project/index.js
      - aws lambda update-function-code --function-name lambda_layar_cicd --zip-file fileb://function.zip
artifacts:
  files:
    - function.zip
